#!/bin/bash

# CDDL HEADER START
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# CDDL HEADER END

# Copyright 2022 Saso Kiselkov. All rights reserved.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
if [[ -z "${BPB_SKIP_LOCAL_REEXEC:-}" ]] && \
    [[ -f "${SCRIPT_DIR}/../workbench/local_build_common.sh" ]]; then
	# shellcheck source=../workbench/local_build_common.sh
	source "${SCRIPT_DIR}/../workbench/local_build_common.sh"
	bpb_maybe_reexec_script "${BASH_SOURCE[0]}" "$@"
fi

# Some Cleanup's

# Delivery File Name
version=$(git describe --abbrev=0 --tags)
version="${version//v/}"
version="${version//V/}"

ZIP_DELIVERY_FILE="BetterPushback_V${version}.zip"

rm -rf BetterPushback_*.zip
rm -rf mac_x64
rm -rf win_x64
rm -rf lin_x64

CMAKE_OPTS_COMMON="-DCMAKE_BUILD_TYPE=Release"

DIST_FILES=(
    'BetterPushback_doors.cfg'					''
    'plg_exclude.cfg'					''
    'COPYING'					''
    'data/msgs/README.txt'			''
    'data/msgs/cc_aliases.cfg'			''
    'objects/tugs/LIVERIES_HOWTO.txt'		''
	'objects/tugs/readme.txt'		''
    'objects/night_lamp.obj'			''
)

function install_xtra_file() {
	FILE="$1"
	DSTDIR="$2"
	if [[ "$DSTDIR" = "//PNG2DDS//" ]]; then
		DSTDIR=""
		XFERCMD="convert"
		TGTFILE="$(basename "$FILE")"
		TGTFILE="${TGTFILE/%.png/.dds}"
	else
		TGTFILE="$(basename "$FILE")"
		XFERCMD="cp"
	fi
	if [[ "$DSTDIR" = "" ]]; then
		DSTDIR="$(dirname "$FILE")"
	fi
	mkdir -p "BetterPushback/$DSTDIR"
	$XFERCMD "$FILE" "BetterPushback/$DSTDIR/$TGTFILE"
}

function install_xtra_files() {
	for (( I=0; $I < ${#DIST_FILES[@]}; I=$I + 2 )); do
		install_xtra_file "${DIST_FILES[$I]}" "${DIST_FILES[$I + 1]}"
	done
}

function install_audio_files() {
	FILES=(
		'connected.opus'
		'disco.opus'
		'done_left.opus'
		'done_right.opus'
		'driving_up.opus'
		'op_complete.opus'
		'plan_end.opus'
		'plan_start.opus'
		'ready2conn.opus'
		'start_pb.opus'
		'start_tow.opus'
		'connected.opus'
		'disco.opus'
		'driving_up.opus'
		'op_complete.opus'
		'plan_end.opus'
		'plan_start.opus'
		'ready2conn.opus'
		'start_pb.opus'
		'start_tow.opus'
		'winch.opus'
	)
	find data/msgs -type f -iname '*.opus' | while read; do
		install_xtra_file "$REPLY" ""
	done
}

function install_icon_files() {
	FILES=(
		'accept_plan.png'
		'conn_first.png'
		'delete_seg.png'
		'place_seg.png'
		'cancel_plan.png'
		'move_view.png'
		'rotate_seg.png'
		'disconnect.png'
		'reconnect.png'
	)
	for DIR in data/icons/[a-z][a-z]; do
		for FILE in ${FILES[@]}; do
			install_xtra_file "$DIR/$FILE" ""
		done
	done
	install_xtra_file "data/icons/en/planner.png" ""
	install_xtra_file "data/icons/en/push-back.png" ""
	install_xtra_file "data/icons/en/conn_first_mb.png" ""
	install_xtra_file "data/icons/en/status.png" ""
}

function install_tug_files() {
	FILES=( $( find objects/tugs/*.tug -type f \
	    '(' -iname '*.obj' -or -iname '*.cfg' -or -iname '*.wav' -or \
	    -iname '*.opus' -or -iname '*.png' ')' ) )
	for FILE in ${FILES[@]}; do
		install_xtra_file "$FILE" ""
	done
}

function install_po_files() {
	xgettext --keyword=_ --language=C  -j -i -o data/po/strings.pot src/*.c
	FILES=( $( find data/po -iname '*.po' ) )
	for FILE in ${FILES[@]}; do
		install_xtra_file "$FILE" ""
	done
}

function install_font_files() {
	FILES=( $( find data/fonts -iname '*.otf' -or -iname '*.ttf' ) )
	for FILE in ${FILES[@]}; do
		install_xtra_file "$FILE" ""
	done
}

function install_override_files() {
	FILES=( $( find objects/override -iname '*.acf' ) )
	for FILE in ${FILES[@]}; do
		install_xtra_file "$FILE" ""
	done
}


cd "${SCRIPT_DIR}"

rm -rf BetterPushback
mkdir -p BetterPushback

set -e

set -- -f
source ./build_xpl.sh 

install_xtra_files
install_po_files
install_audio_files
install_icon_files
install_tug_files
install_override_files
install_font_files

set +e
